### ISSUE TITLE
Connecting a remote interface without creating a VLAN on top

### ISSUE THREAD

**Issue by tedlean** [networkservicemesh/cmd-nse-remote-vlan#18] opened 2022-03-02 15:35 UTC
In order to facilitate a wider range of virtual environments hosting the Kubernetes cluster it could be feasible to allow the injection an interface into the NSC without creating a vlan on top. Some environments uses vlan in the underlay to provide interfaces for the worker-nodes. Here it might not be tolerated that an additional vlan is added on top ending up with a "Q-in-Q" setup.
Therefore it should be possible to have a plain Ethernet interface injected without adding any additional vlan tagging.

**Comment by ljkiraly** [comment] 2022-04-06 06:19
Instead of injection, we agreed offline to go for a cluster break-out option for not adding the extra VLAN tag just connecting the given interface with the virtual interface (which belongs to local mechanism) created in NSC pod.

The general naming convention is used by vpp for vlan sub-interfaces so the base interface name can not follow that naming convention. The base interface name is set in NSM by device-selector file to map to 'via' label. 
So for example the base interface for cluster breakout 'eth2.100' must be renamed to 'eth2_vlan100' (or something like that).

**Comment by tedlean** [comment] 2022-04-06 09:07
Will this naming convention will have impact on the user-provided configuration. 
Currently we have these in the Attractor CR:

**Comment by ljkiraly** [comment] 2022-04-06 09:49
@tedlean I reopen this issue - supposing closed by fault. 

> The "name" is meant to be the name of interface exposed inside the Pod.
> For an ignorant user it would be natural set the name to "eth1.220" if the base-interface is "eth1" and the vlan-id is "220".
> 
> But if I understand you correctly this is not possible/allowed?

No, the base-interface can not be eth1.220, the name of interface exposed inside the Pod can be anything.

**Comment by tedlean** [comment] 2022-04-06 10:45
Okay, so it actually is the naming of the interface on the VM worker-node,  which cannot be "eth1.220". 
 I do not really know how wide-spread a problem this will be. Normally I do not think that the interface provided into to a VM will have any "vlan extension" even though the L2 connectivity is provided by a VLAN in the underlay network.
Still this naming convention probably should be mentioned somewhere. Is it only the vlan setup that has this issue?

**Comment by ljkiraly** [comment] 2022-04-06 12:25
> Okay, so it actually is the naming of the interface on the VM worker-node, which cannot be "eth1.220".

Confirmed.

> Is it only the vlan setup that has this issue? 

Not yet checked but I think any other setup is affected.
When I created a host interface inside vpp using an AF_PACKET interface created by default naming scheme (e.g eth1.220) the cross-connection does not worked. Based on vpp documentation this AF_PACKET is expected to be one side of a veth pair. Maybe vpp handle the "host-eth1.220" as a sub-interface of a host interface, not as a host interface. I have to double check in documentation, but maybe @edwarnicke can correct me.

**Comment by ljkiraly** [comment] 2022-04-07 08:32
@edwarnicke 
> Please note, AF_PACKET can be used to bind to any interface, not just one end of a veth pair.

Thanks, that's fine.
I will try to detail the problem with interface name also since it is an issue on technical level.

> What is the nature of the issue you see when the interface is named eth1.220 ?

Currently the interface created in NSC (by local mechanism type:kernel) is cross-connected with the sub-interface in vpp (created by remote-mechanism type:vlan) - also vlan-tag-rewrite was set on the sub-interface. In the change made by [commit](https://github.com/networkservicemesh/sdk-vpp/pull/546/commits/e38c43d1c0385a3d38c8d9942205cb8d82d0e972)  in case of vlan_id=0 the sub-interface is not created and no vtr is set, the host interface is directly connected to the tap/veth interface of NSC. 

1.  The host interface not getting nor forwarding packets as expected if
   - AF_PACKET interface name is `eth1.220` 
   - the host interface in vpp will be `host-eth1.220` 

2.   The host interface getting and transmitting packets as expected if 
   - AF_PACKET interface name is `eth1_220` 
   - the host interface in vpp will be `host-eth1_220 `

Meantime I figured out that the host interface can be renamed when it is created, but this will cause problem in the code where the interfaces are dumped and filtered by name. If you do not have better suggestion I will handle this in NSM code and eliminate this deviation renaming `host-eth1.220` to `host-eth1_220 ` by SwInterfaceSetInterfaceName

As I see now, with this change we move from a specific (vlan) remote break-out to a generic cluster breakout.

**Comment by edwarnicke** [comment] 2022-04-07 14:03
@ljkiraly Is the interface name the issue, or is it some other characteristic of the kernel interface?

**Comment by ljkiraly** [comment] 2022-04-08 13:43
@edwarnicke Seems that somehow the MTU setting failed (api call HwInterfaceSetMtu) for this renamed interface and the ACL creation was skipped. I double checked and I can confirm that the defined ACLs disables the traffic. 
Also observed problems related to MTU settings - I heard from Zoltan, that he already reported that.

What would be the impact of skipping the ACL creation for the interfaces created for cluster breakout?

**Closed** 2022-05-24 11:09 UTC
Labels: enhancement
